version: '3.8'
services:
  app:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # O comando do Dockerfile será usado:
    # CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000",  "--reload"]